name: 'List Installed Software'

description: 'List the Pixi environment and Node.js/npm versions'

inputs:
  environment:
    description: 'Pixi environment to list'
    required: true

runs:
  using: composite
  steps:
    - name: List installed software
      shell: bash --noprofile --norc -eo pipefail {0}
      run: |
        pixi info
        pixi list --locked --environment "${{ inputs.environment }}"
        echo "python $(python --version)"
        echo "node $(node --version)"
        echo "npm $(npm --version)"
