#/* vim: set filetype=dockerfile : */
FROM travisci/ci-garnet:packer-1515445631-7dfb2e1

ADD . /tmp/bokeh
RUN chown -R travis /tmp/bokeh

USER travis

ENV NO_GIT_FETCH=1
ENV PATH="/home/travis/miniconda/envs/testenv/bin/:/home/travis/miniconda/bin/:${PATH}"
ENV CONDA_REQS="conda=4.6.2 conda-build=3.17.8"
ARG PYTHON

RUN cd /tmp/bokeh && scripts/ci/install.test

RUN rm -rf /tmp/bokeh

# Add some bokeh examples to be run
ENV BOKEH_EXAMPLE_DIR /root/bokeh_examples
COPY examples/models $BOKEH_EXAMPLE_DIR/models
COPY examples/app $BOKEH_EXAMPLE_DIR/app
