Listen 8080

<VirtualHost *:8080>
    ServerName localhost

    ProxyRequests Off
    ProxyPreserveHost On

    ProxyPass "/services/bokeh/ws" "ws://127.0.0.1:5100/ws"
    ProxyPassReverse "/services/bokeh/ws" "ws://127.0.0.1:5100/ws"

    ProxyPass "/services/bokeh/" "http://127.0.0.1:5100/"
    ProxyPassReverse "/services/bokeh/" "http://127.0.0.1:5100/"
</VirtualHost>
