server {
    listen 8080;
    server_name _;

    location /services/bokeh/ {
        proxy_pass http://127.0.0.1:5100/;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Origin $http_origin;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;
        proxy_read_timeout 3s;
        proxy_send_timeout 3s;
        proxy_buffering off;
    }
}
