build:
  - 'docs/**'
  - 'bokehjs/**'
  - 'src/**'
  - 'examples/**'
  - 'MANIFEST.in'
  - 'pyproject.toml'
  - 'setup.py'
  - 'pixi.toml'
  - 'pixi.lock'
  - 'tools/release/**'

codebase:
  - 'src/**'
  - 'examples/**'

typing:
  - 'src/**'

tools:
  - 'tools/**'
  - '!tools/ci/**'
  - 'src/**'

examples:
  - 'src/**'
  - 'examples/**'

unit_test:
  - 'src/**'

jupyter:
  - 'bokehjs/**'
  - 'MANIFEST.in'
  - 'pyproject.toml'
  - 'setup.py'
  - 'pixi.toml'
  - 'pixi.lock'
  - 'tools/release/**'
  - 'src/**'
  - 'examples/output/**'
  - 'examples/server/api/**'
  - 'tests/**'

minimal_deps:
  - 'src/**'

core_deps:
  - 'src/**'

documentation:
  - 'docs/**'
  - 'src/**'
  - 'examples/**'

bokehjs:
  - 'bokehjs/**'
  - 'src/bokeh/jupyter/frontend/**'

full:
  - '**'
  - '!docs/**'
  - '!tools/**'
  - '!bokehjs/**'
  - '!src/**'
  - '!examples/**'

ci:
  - 'tools/ci/**'
