#################################
# Dependabot Configuration File #
#################################

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `/bokehjs` directory
    directory: "/bokehjs"
    # Check the npm registry for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for Pip
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      
