require "./categorical_mapper"
require "./categorical_color_mapper"
require "./color_mapper"
require "./linear_mapper"
require "./linear_color_mapper"
require "./log_color_mapper"
require "./log_mapper"
