build: false

platform:
  - x64

environment:
  matrix:
    # Python 3.6
    - MINICONDA: C:\Miniconda36-x64

init:
  - cmd: set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%
  - cmd: echo %path%
  
install:
  - powershell .\\scripts\\ci\\appveyor\\install.ps1

build_script:
  - powershell .\\scripts\\ci\\appveyor\\build.ps1

test_script:
  - powershell .\\scripts\\ci\\appveyor\\test.ps1

