exclude:
- /bokeh/colors.py
- /bokeh/core/_templates/.*
- /bokeh/sphinxext/.*
- /bokeh/_version.py
- /bokehjs/src/coffee/api/palettes.ts
- /bokehjs/src/coffee/core/util/svg_colors.ts
- /conda.recipe/.*
- /conftest.py
- /docker-tools/.*
- /examples/.*
- /scripts/.*
- /sphinx/.*
- /versioneer.py
component_depth: 1
languages:
- javascript
- python
- script
- typescript
