package: bokeh

platform:
  - linux-64

engine:
   - python=2
   - python=3

before_script:
  - python -V

script: |
  export c_env=/opt/anaconda/conda-bld/
  conda build conda.recipe  --quiet;
  mkdir -p c_env/win-64 c_env/osx-64;
  ls -al;
  ls -al c_env/*;
  conda convert -p win-64 -f c_env/linux-64/bokeh*.tar.bz2;
  ls -al win-64;
  filename=`ls win-64/bokeh*.tar.bz2 | xargs -n 1 basename`;
  echo $filename;
  cp -r win-64/$filename c_env/win-64/$filename;
  conda convert -p osx-64 -f c_env/linux-64/bokeh*.tar.bz2;
  ls -al osx-64/;
  filename=`ls osx-64/bokeh*.tar.bz2 | xargs -n 1 basename`;
  echo $filename
  cp -r osx-64/$filename c_env/osx-64/$filename;

build_targets:
    files: c_env/*/bokeh*.tar.bz2
    channels: 'nightly'

