# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

---
default_stages: [pre-push]
exclude: ^docs/CHANGELOG$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        stages: [pre-commit]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [pre-commit]
      - id: check-yaml
        name: Validate YAML files
        exclude: conda/recipe/meta.yaml
      - id: check-json
        name: Validate JSON files

  - repo: local
    hooks:
      - id: reject-static-docs-links
        name: Reject static links to Bokeh documentation
        entry: '^\s*\.\..*https://docs\.bokeh\.org'
        language: pygrep
        types: [text]
        stages: [pre-commit]

      - id: run-codebase
        name: Run codebase checks
        entry: pytest -n logical --maxprocesses=5 tests/codebase
        language: conda
        pass_filenames: false

      - id: protect-branches
        name: Protect Git branches
        entry: python tools/hooks/protect_branches.py
        language: conda
        pass_filenames: false
