#!/usr/bin/env python

from __future__ import print_function

import bokeh.server.demo

if __name__ == "__main__":
    try:
        bokeh.server.demo.start()
    except KeyboardInterrupt:
        bokeh.server.demo.stop()
        print("Shutting down bokeh-server ...")
