#-----------------------------------------------------------------------------
# Copyright (c) Anaconda, Inc., and Bokeh Contributors.
# All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------

# Standard library imports
from abc import abstractmethod
from datetime import date, datetime
from typing import Literal, Sequence, Unpack

# Bokeh imports
from ..._types import Color, Datetime
from ..formatters import TickFormatter
from .widget import Widget, WidgetInit

class AbstractSliderInit(WidgetInit, total=False):
    orientation: Literal["horizontal", "vertical"]
    title: str | None
    show_value: bool
    direction: Literal["ltr", "rtl"]
    tooltips: bool
    bar_color: Color

class AbstractSlider(Widget):
    @abstractmethod
    def __init__(self, **kwargs: Unpack[AbstractSliderInit]) -> None: ...

    orientation: Literal["horizontal", "vertical"] = ...
    title: str | None = ...
    show_value: bool = ...
    direction: Literal["ltr", "rtl"] = ...
    tooltips: bool = ...
    bar_color: Color = ...

class NumericalSliderInit(AbstractSliderInit, total=False):
    format: str | TickFormatter

class NumericalSlider(AbstractSlider):
    @abstractmethod
    def __init__(self, **kwargs: Unpack[NumericalSliderInit]) -> None: ...

    format: str | TickFormatter = ...

class CategoricalSliderInit(AbstractSliderInit, total=False):
    categories: Sequence[str]
    value: str

class CategoricalSlider(AbstractSlider):
    def __init__(self, **kwargs: Unpack[CategoricalSliderInit]) -> None: ...

    categories: Sequence[str] = ...
    value: str = ...

    @property
    def value_throttled(self) -> str: ...

class SliderInit(NumericalSliderInit, total=False):
    start: float
    end: float
    value: float
    step: float

class Slider(NumericalSlider):
    def __init__(self, **kwargs: Unpack[SliderInit]) -> None: ...

    start: float = ...
    end: float = ...
    value: float = ...
    step: float = ...

    @property
    def value_throttled(self) -> float: ...

class RangeSliderInit(NumericalSliderInit, total=False):
    value: tuple[float, float]
    start: float
    end: float
    step: float

class RangeSlider(NumericalSlider):
    def __init__(self, **kwargs: Unpack[RangeSliderInit]) -> None: ...

    value: tuple[float, float] = ...
    start: float = ...
    end: float = ...
    step: float = ...

    @property
    def value_throttled(self) -> tuple[float, float]: ...

class DateSliderInit(NumericalSliderInit, total=False):
    value: Datetime
    start: Datetime
    end: Datetime
    step: int

class DateSlider(NumericalSlider):
    def __init__(self, **kwargs: Unpack[DateSliderInit]) -> None: ...

    value: Datetime = ...
    start: Datetime = ...
    end: Datetime = ...
    step: int = ...

    @property
    def value_throttled(self) -> Datetime: ...
    @property
    def value_as_datetime(self) -> datetime | None: ...
    @property
    def value_as_date(self) -> date | None: ...

class DateRangeSliderInit(NumericalSliderInit, total=False):
    value: tuple[Datetime, Datetime]
    start: Datetime
    end: Datetime
    step: int

class DateRangeSlider(NumericalSlider):
    def __init__(self, **kwargs: Unpack[DateRangeSliderInit]) -> None: ...

    value: tuple[Datetime, Datetime] = ...
    start: Datetime = ...
    end: Datetime = ...
    step: int = ...

    @property
    def value_throttled(self) -> tuple[Datetime, Datetime]: ...
    @property
    def value_as_datetime(self) -> tuple[datetime, datetime] | None: ...
    @property
    def value_as_date(self) -> tuple[date, date] | None: ...

class DatetimeRangeSliderInit(NumericalSliderInit, total=False):
    value: tuple[Datetime, Datetime]
    start: Datetime
    end: Datetime
    step: int

class DatetimeRangeSlider(NumericalSlider):
    def __init__(self, **kwargs: Unpack[DatetimeRangeSliderInit]) -> None: ...

    value: tuple[Datetime, Datetime] = ...
    start: Datetime = ...
    end: Datetime = ...
    step: int = ...

    @property
    def value_throttled(self) -> tuple[Datetime, Datetime]: ...
    @property
    def value_as_datetime(self) -> tuple[datetime, datetime] | None: ...
