#-----------------------------------------------------------------------------
# Copyright (c) Anaconda, Inc., and Bokeh Contributors.
# All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------

# Standard library imports
from abc import abstractmethod
from typing import Any, Literal, Unpack

# Bokeh imports
from ..._specs import ColorSpec, FontStyleSpec, TextAlignSpec
from ...core.enums import (
    AutosizeModeType as AutosizeMode,
    DateFormatType as DateFormat,
    NumeralLanguageType as NumeralLanguage,
    RoundingFunctionType as RoundingFunction,
)
from ...model.model import Model, ModelInit
from ..comparisons import Comparison
from ..sources import (
    CDSView,
    ColumnDataSource,
    DataDictLike,
    DataSource,
)
from .widget import Widget, WidgetInit

class CellFormatterInit(ModelInit, total=False):
    ...

class CellFormatter(Model):
    @abstractmethod
    def __init__(self, **kwargs: Unpack[CellFormatterInit]) -> None: ...

class CellEditorInit(ModelInit, total=False):
    ...

class CellEditor(Model):
    @abstractmethod
    def __init__(self, **kwargs: Unpack[CellEditorInit]) -> None: ...

class RowAggregatorInit(ModelInit, total=False):
    field_: str

class RowAggregator(Model):
    @abstractmethod
    def __init__(self, **kwargs: Unpack[RowAggregatorInit]) -> None: ...

    field_: str = ...

class StringFormatterInit(CellFormatterInit, total=False):
    font_style: FontStyleSpec
    text_align: TextAlignSpec
    text_color: ColorSpec
    background_color: ColorSpec
    nan_format: str
    null_format: str

class StringFormatter(CellFormatter):
    def __init__(self, **kwargs: Unpack[StringFormatterInit]) -> None: ...

    font_style: FontStyleSpec = ...
    text_align: TextAlignSpec = ...
    text_color: ColorSpec = ...
    background_color: ColorSpec = ...
    nan_format: str = ...
    null_format: str = ...

class ScientificFormatterInit(StringFormatterInit, total=False):
    precision: int
    power_limit_high: int
    power_limit_low: int

class ScientificFormatter(StringFormatter):
    def __init__(self, **kwargs: Unpack[ScientificFormatterInit]) -> None: ...

    precision: int = ...
    power_limit_high: int = ...
    power_limit_low: int = ...

class NumberFormatterInit(StringFormatterInit, total=False):
    format: str
    language: NumeralLanguage
    rounding: RoundingFunction

class NumberFormatter(StringFormatter):
    def __init__(self, **kwargs: Unpack[NumberFormatterInit]) -> None: ...

    format: str = ...
    language: NumeralLanguage = ...
    rounding: RoundingFunction = ...

class BooleanFormatterInit(CellFormatterInit, total=False):
    icon: Literal["check", "check-circle", "check-circle-o", "check-square", "check-square-o"]

class BooleanFormatter(CellFormatter):
    def __init__(self, **kwargs: Unpack[BooleanFormatterInit]) -> None: ...

    icon: Literal["check", "check-circle", "check-circle-o", "check-square", "check-square-o"] = ...

class DateFormatterInit(StringFormatterInit, total=False):
    format: DateFormat | str

class DateFormatter(StringFormatter):
    def __init__(self, **kwargs: Unpack[DateFormatterInit]) -> None: ...

    format: DateFormat | str = ...

class HTMLTemplateFormatterInit(CellFormatterInit, total=False):
    template: str

class HTMLTemplateFormatter(CellFormatter):
    def __init__(self, **kwargs: Unpack[HTMLTemplateFormatterInit]) -> None: ...

    template: str = ...

class StringEditorInit(CellEditorInit, total=False):
    completions: list[str]

class StringEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[StringEditorInit]) -> None: ...

    completions: list[str] = ...

class TextEditorInit(CellEditorInit, total=False):
    ...

class TextEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[TextEditorInit]) -> None: ...

class SelectEditorInit(CellEditorInit, total=False):
    options: list[str]

class SelectEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[SelectEditorInit]) -> None: ...

    options: list[str] = ...

class PercentEditorInit(CellEditorInit, total=False):
    ...

class PercentEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[PercentEditorInit]) -> None: ...

class CheckboxEditorInit(CellEditorInit, total=False):
    ...

class CheckboxEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[CheckboxEditorInit]) -> None: ...

class IntEditorInit(CellEditorInit, total=False):
    step: int

class IntEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[IntEditorInit]) -> None: ...

    step: int = ...

class NumberEditorInit(CellEditorInit, total=False):
    step: float

class NumberEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[NumberEditorInit]) -> None: ...

    step: float = ...

class TimeEditorInit(CellEditorInit, total=False):
    ...

class TimeEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[TimeEditorInit]) -> None: ...

class DateEditorInit(CellEditorInit, total=False):
    ...

class DateEditor(CellEditor):
    def __init__(self, **kwargs: Unpack[DateEditorInit]) -> None: ...

class AvgAggregatorInit(RowAggregatorInit, total=False):
    ...

class AvgAggregator(RowAggregator):
    def __init__(self, **kwargs: Unpack[AvgAggregatorInit]) -> None: ...

class MinAggregatorInit(RowAggregatorInit, total=False):
    ...

class MinAggregator(RowAggregator):
    def __init__(self, **kwargs: Unpack[MinAggregatorInit]) -> None: ...

class MaxAggregatorInit(RowAggregatorInit, total=False):
    ...

class MaxAggregator(RowAggregator):
    def __init__(self, **kwargs: Unpack[MaxAggregatorInit]) -> None: ...

class SumAggregatorInit(RowAggregatorInit, total=False):
    ...

class SumAggregator(RowAggregator):
    def __init__(self, **kwargs: Unpack[SumAggregatorInit]) -> None: ...

class TableColumnInit(ModelInit, total=False):
    field: str
    title: str | None
    width: int
    formatter: CellFormatter
    editor: CellEditor
    sortable: bool
    default_sort: Literal["ascending", "descending"]
    visible: bool
    sorter: Comparison | None

class TableColumn(Model):
    def __init__(self, **kwargs: Unpack[TableColumnInit]) -> None: ...

    field: str = ...
    title: str | None = ...
    width: int = ...
    formatter: CellFormatter = ...
    editor: CellEditor = ...
    sortable: bool = ...
    default_sort: Literal["ascending", "descending"] = ...
    visible: bool = ...
    sorter: Comparison | None = ...

class TableWidgetInit(WidgetInit, total=False):
    source: DataSource
    view: CDSView

class TableWidget(Widget):
    @abstractmethod
    def __init__(self, **kwargs: Unpack[TableWidgetInit]) -> None: ...

    source: DataSource = ...
    view: CDSView = ...

class DataTableInit(TableWidgetInit, total=False):
    autosize_mode: AutosizeMode
    auto_edit: bool
    columns: list[TableColumn]
    fit_columns: bool | None
    frozen_columns: int | None
    frozen_rows: int | None
    sortable: bool
    reorderable: bool
    editable: bool
    selectable: bool | Literal["checkbox"]
    index_position: int | None
    index_header: str
    index_width: int
    scroll_to_selection: bool
    header_row: bool
    row_height: int

class DataTable(TableWidget):
    def __init__(self, **kwargs: Unpack[DataTableInit]) -> None: ...

    autosize_mode: AutosizeMode = ...
    auto_edit: bool = ...
    columns: list[TableColumn] = ...
    fit_columns: bool | None = ...
    frozen_columns: int | None = ...
    frozen_rows: int | None = ...
    sortable: bool = ...
    reorderable: bool = ...
    editable: bool = ...
    selectable: bool | Literal["checkbox"] = ...
    index_position: int | None = ...
    index_header: str = ...
    index_width: int = ...
    scroll_to_selection: bool = ...
    header_row: bool = ...
    row_height: int = ...

    @staticmethod
    def from_data(data: ColumnDataSource | DataDictLike, columns: list[str] | None = None,
        formatters: dict[str, CellFormatter] = {}, **kwargs: Any) -> DataTable: ...

class GroupingInfoInit(ModelInit, total=False):
    getter: str
    aggregators: list[RowAggregator]
    collapsed: bool

class GroupingInfo(Model):
    def __init__(self, **kwargs: Unpack[GroupingInfoInit]) -> None: ...

    getter: str = ...
    aggregators: list[RowAggregator] = ...
    collapsed: bool = ...

class DataCubeInit(DataTableInit, total=False):
    grouping: list[GroupingInfo]
    target: DataSource

class DataCube(DataTable):
    def __init__(self, **kwargs: Unpack[DataCubeInit]) -> None: ...

    grouping: list[GroupingInfo] = ...
    target: DataSource = ...
