#!/usr/bin/env python3

from __future__ import annotations

# Standard library imports
import argparse
import inspect
import json
import posixpath
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
PACKAGE_ROOT = Path(__file__).resolve().parent
MODEL_REFERENCE_ROOT = REPO_ROOT / "docs" / "bokeh" / "source" / "docs" / "reference" / "models"
CLASS_INDEX_PATH = MODEL_REFERENCE_ROOT / "class_index.rst"
SECTION_REGISTRY_PATH = PACKAGE_ROOT / "sections.json"
LEGACY_URLS_PATH = PACKAGE_ROOT / "legacy_urls.json"

GENERATED_MARKER = ".. This file is generated by python -m api_reference. Do not edit."

EXTRA_PUBLIC_API = {
    "formatters": ("bokeh.models.formatters.RELATIVE_DATETIME_CONTEXT",),
    "widgets/inputs": ("bokeh.models.widgets.inputs.ColorMap",),
}

LEGACY_SECTION_LABELS = {
    "plots": ("bokeh.models_plots",),
    "ui/examiner": ("bokeh.models.ui.inspector",),
}


@dataclass(frozen=True)
class ClassReference:
    name: str
    module: str
    section: str
    is_model: bool

    @property
    def target(self) -> str:
        return f"bokeh.models.{self.name}"

    @property
    def docname(self) -> str:
        return f"docs/reference/models/{self.section}/{self.name}/index"


@dataclass(frozen=True)
class SectionReference:
    slug: str
    title: str
    classes: tuple[str, ...]


def _load_sections() -> list[SectionReference]:
    raw_sections = json.loads(SECTION_REGISTRY_PATH.read_text())
    sections = [SectionReference(item["slug"], item["title"], tuple(item["classes"])) for item in raw_sections]

    seen_slugs: set[str] = set()
    seen_classes: dict[str, str] = {}
    for section in sections:
        if not re.fullmatch(r"[a-z_][a-z0-9_]*(?:/[a-z_][a-z0-9_]*)*", section.slug):
            raise RuntimeError(f"invalid model reference section slug: {section.slug!r}")
        if section.slug in seen_slugs:
            raise RuntimeError(f"duplicate model reference section slug: {section.slug!r}")
        seen_slugs.add(section.slug)

        for name in section.classes:
            previous = seen_classes.setdefault(name, section.slug)
            if previous != section.slug:
                raise RuntimeError(f"public class {name!r} occurs in both {previous!r} and {section.slug!r}")

    return sections


def _load_public_classes(sections: list[SectionReference] | None = None) -> list[ClassReference]:
    sys.path.insert(0, str(REPO_ROOT / "src"))

    import bokeh.models as models
    from bokeh.model import Model

    if sections is None:
        sections = _load_sections()
    section_by_name = {name: section.slug for section in sections for name in section.classes}

    public_objects: dict[str, type[Any]] = {}
    seen: set[type[Any]] = set()

    for name in models.__all__:
        obj = getattr(models, name)
        if not inspect.isclass(obj) or obj is Model:
            continue
        if obj in seen:
            raise RuntimeError(f"public class {obj!r} is exported under more than one name")
        seen.add(obj)
        public_objects[name] = obj

    missing = sorted(set(public_objects) - set(section_by_name), key=str.casefold)
    stale = sorted(set(section_by_name) - set(public_objects), key=str.casefold)
    if missing or stale:
        details = []
        if missing:
            details.append(f"unassigned public classes: {', '.join(missing)}")
        if stale:
            details.append(f"unknown registered classes: {', '.join(stale)}")
        raise RuntimeError("; ".join(details))

    classes = [
        ClassReference(name, obj.__module__, section_by_name[name], issubclass(obj, Model))
        for name, obj in public_objects.items()
    ]

    classes.sort(key=lambda ref: ref.name.casefold())

    casefolded: dict[str, str] = {}
    for ref in classes:
        previous = casefolded.setdefault(ref.name.casefold(), ref.name)
        if previous != ref.name:
            raise RuntimeError(f"class page names collide on case-insensitive file systems: {previous!r} and {ref.name!r}")

    return classes


def _heading(title: str, underline: str = "#") -> str:
    return f"{title}\n{underline * len(title)}"


def _render_class_page(ref: ClassReference) -> str:
    # Standard-domain labels are case-insensitive, so a label such as
    # ``bokeh.models.Text`` collides with the ``bokeh.models.text`` module
    # label. The Python-domain object itself provides the stable top-level
    # ``bokeh.models.ClassName`` target; this label preserves module-qualified
    # references such as the existing glyph labels.
    labels = [f"{ref.module}.{ref.name}"]
    unique_labels = tuple(dict.fromkeys(labels))
    label_text = "\n".join(f".. _{label}:" for label in unique_labels)
    title = f"bokeh.models.{ref.name}"

    if ref.is_model:
        directive = f""".. bokeh-model:: {ref.name}
    :module: {ref.module}"""
    else:
        directive = f""".. autoclass:: {ref.target}
    :members:
    :show-inheritance:
    :inherited-members:"""

    return f"""{GENERATED_MARKER}

{label_text}

.. meta::
    :description: API reference for {ref.target}.

{_heading(title)}

{directive}
""".strip() + "\n"


def _relative_class_doc(section: str, name: str) -> str:
    section_dir = posixpath.dirname(section)
    return posixpath.relpath(f"{section}/{name}/index", start=section_dir or ".")


def _render_section_page(section: SectionReference, refs: list[ClassReference]) -> str:
    labels = [f"bokeh.models.{section.slug.replace('/', '.')}", *LEGACY_SECTION_LABELS.get(section.slug, ())]
    label_text = "\n".join(f".. _{label}:" for label in labels)

    class_items = "\n".join(
        f"* :raw-html:`<span id=\"bokeh.models.{ref.name}\"></span>` :class:`~{ref.target}`"
        for ref in refs
    )
    toctree_items = "\n".join(
        f"   {ref.name} <{_relative_class_doc(section.slug, ref.name)}>"
        for ref in refs
    )

    extra_api = ""
    if functions := EXTRA_PUBLIC_API.get(section.slug):
        directives = "\n\n".join(f".. autofunction:: {function}" for function in functions)
        extra_api = f"""

{_heading("Functions", "-")}

{directives}
"""

    return f"""{GENERATED_MARKER}

{label_text}

{_heading(section.title)}

This section groups related classes available from :mod:`bokeh.models`.

{_heading("Classes", "-")}

.. role:: raw-html(raw)
   :format: html

.. rst-class:: bokeh-model-classes

{class_items}

.. toctree::
   :hidden:
   :maxdepth: 1

{toctree_items}
{extra_api}
""".strip() + "\n"


def _render_class_index(refs: list[ClassReference]) -> str:
    targets = [("Model", "bokeh.model.Model")]
    targets.extend((ref.name, ref.target) for ref in refs)
    targets.sort(key=lambda item: item[0].casefold())
    items = [f"   * :class:`~{target}`" for _, target in targets]

    return f"""{GENERATED_MARKER}

.. _bokeh.models.classes:

{_heading("Class index")}

This is an alphabetical list of the public classes available from
:mod:`bokeh.models`. The classes are also grouped by topic in the navigation.

.. hlist::
   :columns: 3

{chr(10).join(items)}
""".strip() + "\n"


def _legacy_pages() -> dict[Path, str]:
    return {
        MODEL_REFERENCE_ROOT / f"{docname}.rst": name
        for docname, name in json.loads(LEGACY_URLS_PATH.read_text()).items()
    }


def _render_legacy_redirect(name: str, target: str) -> str:
    return f"""{GENERATED_MARKER}

:orphan:
:no-search:
:no-sitemap:

.. meta::
    :robots: noindex, follow

{_heading(name)}

.. raw:: html

    <span data-bokeh-model-redirect="{name}"></span>

The reference for :class:`bokeh.models.{name}` has moved to its
:doc:`dedicated class page <{target}>`.
""".strip() + "\n"


def _expected_files() -> dict[Path, str]:
    sections = _load_sections()
    refs = _load_public_classes(sections)
    refs_by_name = {ref.name: ref for ref in refs}
    refs_by_section = {section.slug: [] for section in sections}
    for ref in refs:
        refs_by_section[ref.section].append(ref)

    expected = {MODEL_REFERENCE_ROOT / ref.section / ref.name / "index.rst": _render_class_page(ref) for ref in refs}
    expected[CLASS_INDEX_PATH] = _render_class_index(refs)

    for section in sections:
        expected[MODEL_REFERENCE_ROOT / f"{section.slug}.rst"] = _render_section_page(section, refs_by_section[section.slug])

    for path, name in _legacy_pages().items():
        if name not in refs_by_name:
            raise RuntimeError(f"legacy page {path} references non-public class {name}")
        ref = refs_by_name[name]
        legacy_docname = path.relative_to(MODEL_REFERENCE_ROOT).with_suffix("").as_posix()
        target_docname = f"{ref.section}/{ref.name}/index"
        target = posixpath.relpath(target_docname, start=posixpath.dirname(legacy_docname))
        expected[path] = _render_legacy_redirect(name, target)

    return expected


def _generated_files() -> set[Path]:
    return {
        path
        for path in MODEL_REFERENCE_ROOT.rglob("*.rst")
        if path.read_text().startswith(GENERATED_MARKER)
    }


def _check(expected: dict[Path, str], stale: set[Path]) -> int:
    mismatches = [path for path, contents in expected.items() if not path.exists() or path.read_text() != contents]

    for path in sorted(mismatches):
        print(f"out of date: {path.relative_to(REPO_ROOT)}")
    for path in sorted(stale):
        print(f"stale: {path.relative_to(REPO_ROOT)}")

    if mismatches or stale:
        print("Run python -m api_reference from docs/bokeh to update the API reference.")
        return 1
    return 0


def _write(expected: dict[Path, str], stale: set[Path]) -> None:
    for path, contents in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != contents:
            path.write_text(contents)
            print(f"updated: {path.relative_to(REPO_ROOT)}")

    for path in sorted(stale):
        path.unlink()
        print(f"removed: {path.relative_to(REPO_ROOT)}")


def _clean() -> None:
    for path in sorted(_generated_files()):
        path.unlink()

    for path in sorted(MODEL_REFERENCE_ROOT.rglob("*"), reverse=True):
        if path.is_dir():
            try:
                path.rmdir()
            except OSError:
                pass


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the one-class-per-page bokeh.models API reference")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="check that generated files are up to date")
    mode.add_argument("--clean", action="store_true", help="remove generated API reference sources")
    args = parser.parse_args()

    if args.clean:
        _clean()
        return 0

    expected = _expected_files()
    stale = _generated_files() - set(expected)

    if args.check:
        return _check(expected, stale)

    _write(expected, stale)
    return 0


if __name__ == "__main__":
    sys.exit(main())
