# Standard library imports
from typing import Any

class Packer:
    def __init__(self, *, autoreset: bool = ...) -> None: ...

    def pack(self, obj: Any) -> bytes | None: ...

    def pack_array_header(self, n: int) -> bytes | None: ...
    def pack_map_header(self, n: int) -> bytes | None: ...
    def pack_ext_type(self, typecode: int, data: bytes) -> None: ...

    def bytes(self) -> bytes: ...
    def reset(self) -> None: ...
