from typing import Any, Callable

class AnyWidget:
    model_id: str

    def __init__(self, **kwargs: Any) -> None: ...
    def send(self, content: Any, buffers: list[bytes] | None = None) -> None: ...
    def on_msg(self, callback: Callable[..., Any]) -> None: ...
    def close(self) -> None: ...
    def _repr_mimebundle_(self, **kwargs: Any) -> Any: ...
