name: 'Install Chromium'

description: 'Install specific version of Chromium on Linux (snap-based)'

runs:
  using: composite
  steps:
    - name: Verify platform
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "Linux" ]]; then
          echo "Error: This action only supports Linux (snap-based installation)"
          exit 1
        fi

    - name: Install chromium (Linux)
      shell: bash
      run: |
        INSTALLED=$(chromium --version | cut -d' ' -f2 | cut -d'.' -f1-3)
        EXPECTED=$(echo "$CHROME_VER" | cut -d'.' -f1-3)

        echo "Currently installed Chromium $INSTALLED; expected $EXPECTED"

        if [[ "$INSTALLED" = "$EXPECTED" ]]; then
          echo "Using pre-installed version of chromium"
        else
          URL=https://github.com/bokeh/chromium/raw/main/linux/$CHROME_VER
          wget --no-verbose $URL/$CHROME_REV.assert
          wget --no-verbose $URL/$CHROME_REV.snap

          sudo snap ack $CHROME_REV.assert
          sudo snap install $CHROME_REV.snap
        fi
