# Standard library imports
from dataclasses import dataclass
from typing import Literal, Sequence

# Bokeh imports
from .._types import Datetime, TextLike
from ..core.enums import (
    AlignType as Align,
    AutoType as Auto,
    LabelOrientationType as LabelOrientation,
)
from ..core.has_props import abstract
from ..core.property_mixins import ScalarFillProps, ScalarLineProps, ScalarTextProps
from .formatters import (
    BasicTickFormatter,
    CategoricalTickFormatter,
    DatetimeTickFormatter,
    LogTickFormatter,
    MercatorTickFormatter,
    TickFormatter,
)
from .labeling import LabelingPolicy
from .ranges import Factor
from .renderers import GuideRenderer
from .tickers import (
    BasicTicker,
    CategoricalTicker,
    DatetimeTicker,
    LogTicker,
    MercatorTicker,
    Ticker,
)

@abstract
@dataclass(init=False)
class Axis(GuideRenderer):

    dimension: Auto | Literal[0, 1] = ...

    face: Auto | Literal["front", "back"] = ...

    bounds: Auto | tuple[float, float] | tuple[Datetime, Datetime] = ...

    ticker: Ticker | Sequence[float] = ...

    formatter: TickFormatter = ...

    axis_label: TextLike | None = ...

    axis_label_standoff: int = ...

    axis_label_orientation: LabelOrientation | float = ...

    axis_label_align: Align = ...

    axis_label_props: ScalarTextProps = ...

    major_label_standoff: int = ...

    major_label_orientation: LabelOrientation | float = ...

    major_label_overrides: dict[float | str, TextLike] = ...

    major_label_policy: LabelingPolicy = ...

    major_label_props: ScalarTextProps = ...

    axis_props: ScalarLineProps = ...

    major_tick_props: ScalarLineProps = ...

    major_tick_in: int = ...

    major_tick_out: int = ...

    minor_tick_props: ScalarLineProps = ...

    minor_tick_in: int = ...

    minor_tick_out: int = ...

    fixed_location: None | float | Factor = ...

    background_props: ScalarFillProps = ...

@abstract
@dataclass(init=False)
class ContinuousAxis(Axis):
    ...

@dataclass
class LinearAxis(ContinuousAxis):
    ...

    ticker: BasicTicker = ...

    formatter: BasicTickFormatter = ...

@dataclass
class LogAxis(ContinuousAxis):
    ...

    ticker: LogTicker = ...

    formatter: LogTickFormatter = ...

@dataclass
class CategoricalAxis(Axis):

    ticker: CategoricalTicker = ...

    formatter: CategoricalTickFormatter = ...

    separator_props: ScalarLineProps = ...

    group_props: ScalarTextProps = ...

    group_label_orientation: LabelOrientation | float = ...

    subgroup_props: ScalarTextProps = ...

    subgroup_label_orientation: LabelOrientation | float = ...

@dataclass
class DatetimeAxis(LinearAxis):
    ...

    ticker: DatetimeTicker = ...

    formatter: DatetimeTickFormatter = ...

@dataclass
class MercatorAxis(LinearAxis):
    ...

    ticker: MercatorTicker = ...

    formatter: MercatorTickFormatter = ...
