#-----------------------------------------------------------------------------
# Copyright (c) Anaconda, Inc., and Bokeh Contributors.
# All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------

# Standard library imports
from abc import abstractmethod
from typing import Any, Sequence, Unpack

# Bokeh imports
from ..core.enums import (
    AutoType as Auto,
    ContextWhichType as ContextWhich,
    LatLonType as LatLon,
    LocationType as Location,
    NumeralLanguageType as NumeralLanguage,
    ResolutionTypeType as ResolutionType,
    RoundingFunctionType as RoundingFunction,
)
from ..model.model import Model, ModelInit
from .tickers import Ticker

class TickFormatterInit(ModelInit, total=False):
    ...

class TickFormatter(Model):
    @abstractmethod
    def __init__(self, **kwargs: Unpack[TickFormatterInit]) -> None: ...

class BasicTickFormatterInit(TickFormatterInit, total=False):
    precision: Auto | int
    use_scientific: bool
    power_limit_high: int
    power_limit_low: int

class BasicTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[BasicTickFormatterInit]) -> None: ...

    precision: Auto | int = ...
    use_scientific: bool = ...
    power_limit_high: int = ...
    power_limit_low: int = ...

class MercatorTickFormatterInit(BasicTickFormatterInit, total=False):
    dimension: LatLon | None

class MercatorTickFormatter(BasicTickFormatter):
    def __init__(self, **kwargs: Unpack[MercatorTickFormatterInit]) -> None: ...

    dimension: LatLon | None = ...

class NumeralTickFormatterInit(TickFormatterInit, total=False):
    format: str
    language: NumeralLanguage
    rounding: RoundingFunction

class NumeralTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[NumeralTickFormatterInit]) -> None: ...

    format: str = ...
    language: NumeralLanguage = ...
    rounding: RoundingFunction = ...

class PrintfTickFormatterInit(TickFormatterInit, total=False):
    format: str

class PrintfTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[PrintfTickFormatterInit]) -> None: ...

    format: str = ...

class LogTickFormatterInit(TickFormatterInit, total=False):
    ticker: Ticker | None
    min_exponent: int

class LogTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[LogTickFormatterInit]) -> None: ...

    ticker: Ticker | None = ...
    min_exponent: int = ...

class CategoricalTickFormatterInit(TickFormatterInit, total=False):
    ...

class CategoricalTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[CategoricalTickFormatterInit]) -> None: ...

class CustomJSTickFormatterInit(TickFormatterInit, total=False):
    args: dict[str, Any]
    code: str

class CustomJSTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[CustomJSTickFormatterInit]) -> None: ...

    args: dict[str, Any] = ...
    code: str = ...

class DatetimeTickFormatterInit(TickFormatterInit, total=False):
    microseconds: str
    milliseconds: str
    seconds: str
    minsec: str
    minutes: str
    hourmin: str
    hours: str
    days: str
    months: str
    years: str
    strip_leading_zeros: bool | Sequence[ResolutionType]
    boundary_scaling: bool
    hide_repeats: bool
    context: str | DatetimeTickFormatter | None
    context_which: ContextWhich
    context_location: Location

class DatetimeTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[DatetimeTickFormatterInit]) -> None: ...

    microseconds: str = ...
    milliseconds: str = ...
    seconds: str = ...
    minsec: str = ...
    minutes: str = ...
    hourmin: str = ...
    hours: str = ...
    days: str = ...
    months: str = ...
    years: str = ...
    strip_leading_zeros: bool | Sequence[ResolutionType] = ...
    boundary_scaling: bool = ...
    hide_repeats: bool = ...
    context: str | DatetimeTickFormatter | None = ...
    context_which: ContextWhich = ...
    context_location: Location = ...

class TimedeltaTickFormatterInit(TickFormatterInit, total=False):
    nanoseconds: str
    microseconds: str
    milliseconds: str
    seconds: str
    minsec: str
    minutes: str
    hourmin: str
    hours: str
    days: str
    strip_leading_zeros: bool | Sequence[ResolutionType]
    hide_repeats: bool
    context: str | TimedeltaTickFormatter | None
    context_which: ContextWhich
    context_location: Location

class TimedeltaTickFormatter(TickFormatter):
    def __init__(self, **kwargs: Unpack[TimedeltaTickFormatterInit]) -> None: ...

    nanoseconds: str = ...
    microseconds: str = ...
    milliseconds: str = ...
    seconds: str = ...
    minsec: str = ...
    minutes: str = ...
    hourmin: str = ...
    hours: str = ...
    days: str = ...
    strip_leading_zeros: bool | Sequence[ResolutionType] = ...
    hide_repeats: bool = ...
    context: str | TimedeltaTickFormatter | None = ...
    context_which: ContextWhich = ...
    context_location: Location = ...

def CONTEXTUAL_DATETIME_FORMATTER() -> DatetimeTickFormatter: ...

def CONTEXTUAL_TIMEDELTA_FORMATTER() -> TimedeltaTickFormatter: ...
