# Standard library imports
from dataclasses import dataclass
from typing import Literal

# Bokeh imports
from .._types import (
    AngleSpec,
    DataSpec,
    DistanceSpec,
    FillProps,
    HatchProps,
    ImageProps,
    LineProps,
    MarkerSpec,
    NonNegative,
    NullDistanceSpec,
    NumberSpec,
    ScalarFillProps,
    ScalarHatchProps,
    ScalarLineProps,
    SizeSpec,
    StringSpec,
    TextProps,
)
from ..core.enums import (
    DirectionType as Direction,
    ImageOriginType as ImageOrigin,
    OutlineShapeNameType as OutlineShapeName,
    PaletteType as Palette,
    RadiusDimensionType as RadiusDimension,
    StepModeType as StepMode,
)
from ..core.has_props import abstract
from ..core.property_aliases import (
    Anchor,
    BorderRadius,
    Padding,
    TextAnchor,
)
from .callbacks import CustomJS
from .glyph import (
    ConnectedXYGlyph,
    FillGlyph,
    HatchGlyph,
    LineGlyph,
    RadialGlyph,
    TextGlyph,
    XYGlyph,
)
from .mappers import ColorMapper, StackColorMapper

@abstract
@dataclass(init=False)
class Marker(XYGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    hit_dilation: NonNegative[float] = ...

    size: SizeSpec = ...

    angle: AngleSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@abstract
@dataclass(init=False)
class LRTBGlyph(LineGlyph, FillGlyph, HatchGlyph):

    border_radius: BorderRadius = ...

@dataclass
class AnnularWedge(XYGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    inner_radius: DistanceSpec = ...

    outer_radius: DistanceSpec = ...

    start_angle: AngleSpec = ...

    end_angle: AngleSpec = ...

    direction: Direction = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Annulus(XYGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    inner_radius: DistanceSpec = ...

    outer_radius: DistanceSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Arc(XYGlyph, LineGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    radius: DistanceSpec = ...

    start_angle: AngleSpec = ...

    end_angle: AngleSpec = ...

    direction: Direction = ...

    line_props: LineProps = ...

@dataclass
class Bezier(LineGlyph):

    x0: NumberSpec = ...

    y0: NumberSpec = ...

    x1: NumberSpec = ...

    y1: NumberSpec = ...

    cx0: NumberSpec = ...

    cy0: NumberSpec = ...

    cx1: NumberSpec = ...

    cy1: NumberSpec = ...

    line_props: LineProps = ...

@dataclass
class Block(LRTBGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    width: DistanceSpec = ...

    height: DistanceSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Circle(RadialGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    radius: DistanceSpec = ...

    radius_dimension: RadiusDimension = ...

    hit_dilation: NonNegative[float] = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Ellipse(XYGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    width: DistanceSpec = ...

    height: DistanceSpec = ...

    angle: AngleSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class HArea(LineGlyph, FillGlyph, HatchGlyph):

    x1: NumberSpec = ...

    x2: NumberSpec = ...

    y: NumberSpec = ...

    fill_props: ScalarFillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class HAreaStep(FillGlyph, HatchGlyph):

    x1: NumberSpec = ...

    x2: NumberSpec = ...

    y: NumberSpec = ...

    step_mode: StepMode = ...

    fill_props: ScalarFillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class HBar(LRTBGlyph):

    y: NumberSpec = ...

    height: DistanceSpec = ...

    left: NumberSpec = ...

    right: NumberSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class HexTile(LineGlyph, FillGlyph, HatchGlyph):

    size: float = ...

    aspect_scale: float = ...

    r: NumberSpec = ...

    q: NumberSpec = ...

    scale: NumberSpec = ...

    orientation: str = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@abstract
@dataclass(init=False)
class ImageBase(XYGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    dw: DistanceSpec = ...

    dh: DistanceSpec = ...

    image_props: ImageProps = ...

    dilate: bool = ...

    origin: ImageOrigin = ...

    anchor: Anchor = ...

@dataclass
class Image(ImageBase):

    image: NumberSpec = ...

    color_mapper: ColorMapper | Palette = ...

@dataclass
class ImageRGBA(ImageBase):

    image: NumberSpec = ...

@dataclass
class ImageStack(ImageBase):

    image: NumberSpec = ...

    color_mapper: StackColorMapper = ...

@dataclass
class ImageURL(XYGlyph):

    url: StringSpec = ...

    x: NumberSpec = ...

    y: NumberSpec = ...

    w: NullDistanceSpec = ...

    h: NullDistanceSpec = ...

    angle: AngleSpec = ...

    global_alpha: NumberSpec = ...

    dilate: bool = ...

    anchor: Anchor = ...

    retry_attempts: int = ...

    retry_timeout: int = ...

@dataclass
class Line(ConnectedXYGlyph, LineGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    line_props: ScalarLineProps = ...

@dataclass
class MultiLine(LineGlyph):

    xs: NumberSpec = ...

    ys: NumberSpec = ...

    line_props: LineProps = ...

@dataclass
class MultiPolygons(LineGlyph, FillGlyph, HatchGlyph):

    xs: NumberSpec = ...

    ys: NumberSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Ngon(RadialGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    radius: DistanceSpec = ...

    angle: AngleSpec = ...

    n: NumberSpec = ...

    radius_dimension: RadiusDimension = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Patch(ConnectedXYGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    line_props: ScalarLineProps = ...

    fill_props: ScalarFillProps = ...

    hatch_props: ScalarHatchProps = ...

@dataclass
class Patches(LineGlyph, FillGlyph, HatchGlyph):

    xs: NumberSpec = ...

    ys: NumberSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Quad(LRTBGlyph):

    left: NumberSpec = ...

    right: NumberSpec = ...

    bottom: NumberSpec = ...

    top: NumberSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Quadratic(LineGlyph):

    x0: NumberSpec = ...

    y0: NumberSpec = ...

    x1: NumberSpec = ...

    y1: NumberSpec = ...

    cx: NumberSpec = ...

    cy: NumberSpec = ...

    line_props: LineProps = ...

@dataclass
class Ray(XYGlyph, LineGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    angle: AngleSpec = ...

    length: DistanceSpec = ...

    line_props: LineProps = ...

@dataclass
class Rect(XYGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    width: DistanceSpec = ...

    height: DistanceSpec = ...

    angle: AngleSpec = ...

    border_radius: BorderRadius = ...

    dilate: bool = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Scatter(Marker):

    marker: MarkerSpec = ...

    defs: dict[str, CustomJS] = ...

@dataclass
class Segment(LineGlyph):

    x0: NumberSpec = ...

    y0: NumberSpec = ...

    x1: NumberSpec = ...

    y1: NumberSpec = ...

    line_props: LineProps = ...

@dataclass
class Step(XYGlyph, LineGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    line_props: ScalarLineProps = ...

    mode: StepMode = ...

@dataclass
class Text(XYGlyph, TextGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    text: StringSpec = ...

    angle: AngleSpec = ...

    x_offset: NumberSpec = ...

    y_offset: NumberSpec = ...

    anchor: DataSpec[TextAnchor] = ...

    padding: Padding = ...

    border_radius: BorderRadius = ...

    outline_shape: DataSpec[OutlineShapeName] = ...

    text_props: TextProps = ...

    background_fill_props: FillProps = ...

    background_hatch_props: HatchProps = ...

    border_line_props: LineProps = ...

@abstract
@dataclass(init=False)
class MathTextGlyph(Text):
    ...

@dataclass
class MathMLGlyph(MathTextGlyph):
    ...

@dataclass
class TeXGlyph(MathTextGlyph):

    macros: dict[str, str | tuple[str, int]] = ...

    display: Literal["inline", "block", "auto"] = ...

@dataclass
class VArea(FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y1: NumberSpec = ...

    y2: NumberSpec = ...

    fill_props: ScalarFillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class VAreaStep(FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y1: NumberSpec = ...

    y2: NumberSpec = ...

    step_mode: StepMode = ...

    fill_props: ScalarFillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class VBar(LRTBGlyph):

    x: NumberSpec = ...

    width: DistanceSpec = ...

    bottom: NumberSpec = ...

    top: NumberSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class Wedge(XYGlyph, LineGlyph, FillGlyph, HatchGlyph):

    x: NumberSpec = ...

    y: NumberSpec = ...

    radius: DistanceSpec = ...

    start_angle: AngleSpec = ...

    end_angle: AngleSpec = ...

    direction: Direction = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class HSpan(LineGlyph):

    y: NumberSpec = ...

    line_props: LineProps = ...

@dataclass
class VSpan(LineGlyph):

    x: NumberSpec = ...

    line_props: LineProps = ...

@dataclass
class HStrip(LineGlyph, FillGlyph, HatchGlyph):

    y0: NumberSpec = ...

    y1: NumberSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...

@dataclass
class VStrip(LineGlyph, FillGlyph, HatchGlyph):

    x0: NumberSpec = ...

    x1: NumberSpec = ...

    line_props: LineProps = ...

    fill_props: FillProps = ...

    hatch_props: HatchProps = ...
