name: bk-test
channels:
  - conda-forge
dependencies:
  - python=3.9

  # runtime
  - contourpy >=1
  - jinja2 >=2.7
  - numpy >=1.11.3
  - packaging >=16.8
  - pillow >=4.0
  - python-dateutil >=2.1
  - pyyaml >=3.10
  - tornado >=5
  - typing_extensions >=3.10.0
  - xyzservices>=2021.09.1

  # tests
  - beautifulsoup4
  - channels
  - click
  - colorama
  - colorcet
  - coverage
  - django 3.*
  - firefox =>96
  - flake8
  - flaky
  - geckodriver
  - ipython
  - isort 5.8
  - mock
  - nbconvert >=5.4
  - networkx
  - nodejs 16.*
  - pandas
  - pre-commit
  - psutil
  - pydot
  - pygments
  - pytest 6.2*
  - pytest-asyncio
  - pytest-cov >=1.8.1
  - pytest-html
  - pytest-xdist
  - requests >=1.2.3
  - scipy
  - selenium 4.2
  - toml

  # examples
  - django
  - flask >=1.0
  - h5py
  - icalendar
  - networkx
  - notebook
  - pyshp
  - scikit-learn
  - sympy

  # pip dependencies
  - pip
  - pip:
    - mypy >=0.971
    # docs
    - autoclasstoc
    - pydata_sphinx_theme >=0.9
    - requests-unixsocket >= 0.3.0
    - sphinx >5.1
    - sphinx-copybutton
    - sphinx-design
    - sphinxext-opengraph
    # tests
    - flake8-pyi
    - pandas-stubs
    - types-boto
    - types-colorama
    - types-mock
    - types-pillow
    - types-pyyaml
    - types-requests
