name: bk-test
channels:
  - conda-forge
dependencies:
  - python=3.10

  - conda-build 24*    # pre .conda format
  - conda-verify 3.4*
  - libiconv
  - nodejs 24.*
  - python-build
  - setuptools
  - yaml
