#!/bin/bash

set -e # exit on error
set -x # echo commands

# install build time dependencies
BUILD_DEPS=`python scripts/deps.py build`
conda install --yes ${BUILD_DEPS}

# install NPM dependencies and build BokehJS
pushd bokehjs
npm install
node_modules/.bin/gulp build
popd

# build a noarch conda package for Bokeh using the just-built BokehJS
conda build conda.recipe --quiet --no-test --no-anaconda-upload

cd ${HOME}

# upload the noarch directory for later jobs in this build
tar czf conda-bld-noarch.tgz "miniconda/conda-bld/noarch"
artifacts upload                        \
    --bucket "bokeh-travis"             \
    --target-paths "${TRAVIS_BUILD_ID}" \
    conda-bld-noarch.tgz

# upload the BokehJS build directory for later jobs in this build
tar czf bokehjs-build.tgz "build/bokeh/bokeh/bokehjs/build"
artifacts upload                        \
    --bucket "bokeh-travis"             \
    --target-paths "${TRAVIS_BUILD_ID}" \
    bokehjs-build.tgz
