#!/bin/bash

set -e # exit on error
set -x # echo commands

# install NPM dependencies and build JS examples
pushd bokehjs
npm install
node_modules/.bin/gulp examples --no-build
popd

# install Bokeh sample data needed by examples
python -c 'import bokeh; bokeh.sampledata.download(progress=False)'
