#!/bin/bash

set -e # exit on error
set -x # echo commands

# install NPM dependencies
pushd bokehjs
npm install --no-save --no-progress phantomjs
popd

if  [[ ! -z "${MINIMAL}" ]]; then
    conda remove --yes --quiet --no-pin pandas scipy notebook scikit-learn sympy flask
fi
