#!/bin/bash

set -e # exit on error
set -x # echo commands

# install NPM dependencies and build JS examples
pushd bokehjs
npm install --no-save --no-progress
node_modules/.bin/gulp examples --no-build
popd
