#!/bin/bash

set -e # exit on error
set -x # echo commands

pushd bokehjs
node_modules/.bin/gulp scripts:compile --emit-error
node_modules/.bin/gulp test:compile --emit-error
popd

py.test -m api

py.test -m sampledata

py.test -m quality
