#!/bin/bash

set -e # exit on error
set -x # echo commands

pushd bokehjs
node make scripts:compile --emit-error

node make test:compile --emit-error

node make tslint
popd

py.test -m sampledata

py.test -m quality
