#!/bin/bash

set -e # exit on error
set -x # echo commands

pushd bokehjs
node gulpfile.js scripts:compile --emit-error

node gulpfile.js test:compile --emit-error

node gulpfile.js tslint
popd

py.test -m sampledata

py.test -m quality
