#!/bin/bash

set -e # exit on error
set -x # echo commands

if  [[ ! -z "${TRAVIS_TAG}" ]]; then
    echo
    echo "SKIPPING TEST STAGE SCRIPT --- This is a build for release tag ${TRAVIS_TAG}"
    echo
    exit 0
fi

[[ "$(python --version | cut -d' ' -f2)" == "${PYTHON:-3.7}"* ]]

bokeh info

bash "scripts/ci/test.${GROUP}"
