# Standard library imports
from dataclasses import dataclass
from typing import Sequence

# Bokeh imports
from ..._types import (
    Coordinate,
    CoordinateLike,
    CoordinateSpec,
    NonNegative,
    Positive,
)
from ...core.enums import (
    CoordinateUnitsType as CoordinateUnits,
    DimensionType as Dimension,
    MovableType as Movable,
    ResizableType as Resizable,
)
from ...core.property_aliases import BorderRadius
from ...core.property_mixins import (
    LineProps,
    ScalarFillProps,
    ScalarHatchProps,
    ScalarLineProps,
)
from ...model import Model
from ..nodes import BoxNodes
from .annotation import Annotation, DataAnnotation
from .arrows import ArrowHead

@dataclass
class AreaVisuals(Model):

    line_props: ScalarLineProps = ...

    fill_props: ScalarFillProps = ...

    hatch_props: ScalarHatchProps = ...

    hover_line_props: ScalarLineProps = ...

    hover_fill_props: ScalarFillProps = ...

    hover_hatch_props: ScalarHatchProps = ...

@dataclass
class BoxInteractionHandles(Model):

    all: AreaVisuals = ...

    move: AreaVisuals | None = ...
    resize: AreaVisuals | None = ...

    sides: AreaVisuals | None = ...
    corners: AreaVisuals | None = ...

    left: AreaVisuals | None = ...
    right: AreaVisuals | None = ...
    top: AreaVisuals | None = ...
    bottom: AreaVisuals | None = ...

    top_left: AreaVisuals | None = ...
    top_right: AreaVisuals | None = ...
    bottom_left: AreaVisuals | None = ...
    bottom_right: AreaVisuals | None = ...

@dataclass
class BoxAnnotation(Annotation, AreaVisuals):

    left: Coordinate = ...

    right: Coordinate = ...

    top: Coordinate = ...

    bottom: Coordinate = ...

    left_units: CoordinateUnits = ...

    right_units: CoordinateUnits = ...

    top_units: CoordinateUnits = ...

    bottom_units: CoordinateUnits = ...

    left_limit: Coordinate | None = ...

    right_limit: Coordinate | None = ...

    top_limit: Coordinate | None = ...

    bottom_limit: Coordinate | None = ...

    min_width: NonNegative[float] = ...

    min_height: NonNegative[float] = ...

    max_width: Positive[float] = ...

    max_height: Positive[float] = ...

    border_radius: BorderRadius = ...

    editable: bool = ...

    resizable: Resizable = ...

    movable: Movable = ...

    symmetric: bool = ...

    use_handles: bool = ...

    handles: BoxInteractionHandles | AreaVisuals = ...

    inverted: bool = ...

    @property
    def nodes(self) -> BoxNodes: ...

@dataclass
class Band(DataAnnotation):

    lower: CoordinateSpec = ...

    upper: CoordinateSpec = ...

    base: CoordinateSpec = ...

    dimension: Dimension = ...

    line_props: ScalarLineProps = ...

    fill_props: ScalarFillProps = ...

@dataclass
class PolyAnnotation(Annotation):

    xs: Sequence[CoordinateLike] = ...

    xs_units: CoordinateUnits = ...

    ys: Sequence[CoordinateLike] = ...

    ys_units: CoordinateUnits = ...

    editable: bool = ...

    line_props: ScalarLineProps = ...

    fill_props: ScalarFillProps = ...

    hatch_props: ScalarHatchProps = ...

    hover_line_props: ScalarLineProps = ...

    hover_fill_props: ScalarFillProps = ...

    hover_hatch_props: ScalarHatchProps = ...

@dataclass
class Slope(Annotation):

    gradient: float | None = ...

    y_intercept: float | None = ...

    line_props: ScalarLineProps = ...

    above_fill_props: ScalarFillProps = ...

    above_hatch_props: ScalarHatchProps = ...

    below_fill_props: ScalarFillProps = ...

    below_hatch_props: ScalarHatchProps = ...

@dataclass
class Span(Annotation):

    location: CoordinateLike | None = ...

    location_units: CoordinateUnits = ...

    dimension: Dimension = ...

    editable: bool = ...

    line_props: ScalarLineProps = ...

    hover_line_props: ScalarLineProps = ...

@dataclass
class Whisker(DataAnnotation):

    lower: CoordinateSpec = ...

    lower_head: ArrowHead | None = ...

    upper: CoordinateSpec = ...

    upper_head: ArrowHead | None = ...

    base: CoordinateSpec = ...

    dimension: Dimension = ...

    line_props: LineProps = ...
