declare module "styles/annotations.css"        { declare const css: string; export default css }
declare module "styles/buttons.css"            { declare const css: string; export default css }
declare module "styles/clearfix.css"           { declare const css: string; export default css }
declare module "styles/icons.css"              { declare const css: string; export default css }
declare module "styles/logo.css"               { declare const css: string; export default css }
declare module "styles/menus.css"              { declare const css: string; export default css }
declare module "styles/notebook.css"           { declare const css: string; export default css }
declare module "styles/root.css"               { declare const css: string; export default css }
declare module "styles/tabs.css"               { declare const css: string; export default css }
declare module "styles/tiles.css"              { declare const css: string; export default css }
declare module "styles/toolbar.css"            { declare const css: string; export default css }
declare module "styles/tooltips.css"           { declare const css: string; export default css }
declare module "styles/widgets/choices.css"    { declare const css: string; export default css }
declare module "styles/widgets/flatpickr.css"  { declare const css: string; export default css }
declare module "styles/widgets/inputs.css"     { declare const css: string; export default css }
declare module "styles/widgets/nouislider.css" { declare const css: string; export default css }
declare module "styles/widgets/slickgrid.css"  { declare const css: string; export default css }
declare module "styles/widgets/sliders.css"    { declare const css: string; export default css }
declare module "styles/widgets/tables.css"     { declare const css: string; export default css }
