import "./root"
import "icons.css"

export const bk_tool_icon_box_select = "bk-tool-icon-box-select"
export const bk_tool_icon_box_zoom = "bk-tool-icon-box-zoom"
export const bk_tool_icon_zoom_in = "bk-tool-icon-zoom-in"
export const bk_tool_icon_zoom_out = "bk-tool-icon-zoom-out"
export const bk_tool_icon_help = "bk-tool-icon-help"
export const bk_tool_icon_hover = "bk-tool-icon-hover"
export const bk_tool_icon_crosshair = "bk-tool-icon-crosshair"
export const bk_tool_icon_lasso_select = "bk-tool-icon-lasso-select"
export const bk_tool_icon_pan = "bk-tool-icon-pan"
export const bk_tool_icon_xpan = "bk-tool-icon-xpan"
export const bk_tool_icon_ypan = "bk-tool-icon-ypan"
export const bk_tool_icon_range = "bk-tool-icon-range"
export const bk_tool_icon_polygon_select = "bk-tool-icon-polygon-select"
export const bk_tool_icon_redo = "bk-tool-icon-redo"
export const bk_tool_icon_reset = "bk-tool-icon-reset"
export const bk_tool_icon_save = "bk-tool-icon-save"
export const bk_tool_icon_tap_select = "bk-tool-icon-tap-select"
export const bk_tool_icon_undo = "bk-tool-icon-undo"
export const bk_tool_icon_wheel_pan = "bk-tool-icon-wheel-pan"
export const bk_tool_icon_wheel_zoom = "bk-tool-icon-wheel-zoom"
export const bk_tool_icon_box_edit = "bk-tool-icon-box-edit"
export const bk_tool_icon_freehand_draw = "bk-tool-icon-freehand-draw"
export const bk_tool_icon_poly_draw = "bk-tool-icon-poly-draw"
export const bk_tool_icon_point_draw = "bk-tool-icon-point-draw"
export const bk_tool_icon_poly_edit = "bk-tool-icon-poly-edit"
