# Standard library imports
from dataclasses import dataclass

# Bokeh imports
from ...._types import (
    Alpha,
    Angle,
    AngleSpec,
    Color,
    CoordinateLike,
    NullStringSpec,
    NumberSpec,
)
from ....core.enums import (
    AngleUnitsType as AngleUnits,
    CoordinateUnitsType as CoordinateUnits,
    FontStyleType as FontStyle,
    TextAlignType as TextAlign,
    VerticalAlignType as VerticalAlign,
)
from ....core.property_aliases import BorderRadius, Padding
from ....core.property_mixins import (
    FillProps,
    LineProps,
    ScalarFillProps,
    ScalarHatchProps,
    ScalarLineProps,
    ScalarTextProps,
)
from ..annotation import DataAnnotation
from .html_annotation import HTMLAnnotation

@dataclass
class HTMLTextAnnotation(HTMLAnnotation):

    padding: Padding = ...

    border_radius: BorderRadius = ...

    background_props: ScalarFillProps = ...

    background_hatch_props: ScalarHatchProps = ...

    border_props: ScalarLineProps = ...

@dataclass
class HTMLLabel(HTMLTextAnnotation):

    x: CoordinateLike = ...

    x_units: CoordinateUnits = ...

    y: CoordinateLike = ...

    y_units: CoordinateUnits = ...

    text: str = ...

    angle: Angle = ...

    angle_units: AngleUnits = ...

    x_offset: float = ...

    y_offset: float = ...

    text_props: ScalarTextProps = ...

@dataclass
class HTMLLabelSet(HTMLAnnotation, DataAnnotation):

    x: NumberSpec = ...

    x_units: CoordinateUnits = ...

    y: NumberSpec = ...

    y_units: CoordinateUnits = ...

    text: NullStringSpec = ...

    angle: AngleSpec = ...

    x_offset: NumberSpec = ...

    y_offset: NumberSpec = ...

    background_props: FillProps = ...

    border_props: LineProps = ...

@dataclass
class HTMLTitle(HTMLTextAnnotation):

    text: str = ...

    vertical_align: VerticalAlign = ...

    align: TextAlign = ...

    text_line_height: float = ...

    offset: float = ...

    standoff: float = ...

    text_font: str = ...

    text_font_size: str = ...

    text_font_style: FontStyle = ...

    text_color: Color = ...

    text_outline_color: Color | None = ...

    text_alpha: Alpha = ...
