#!/usr/bin/env python3

from __future__ import annotations

# Standard library imports
import argparse
import inspect
import posixpath
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
MODEL_REFERENCE_ROOT = REPO_ROOT / "docs" / "bokeh" / "source" / "docs" / "reference" / "models"
CLASS_INDEX_PATH = MODEL_REFERENCE_ROOT / "class_index.rst"

GENERATED_MARKER = ".. This file is generated by python -m tools.api_reference. Do not edit."

TOP_CATEGORY_ORDER = (
    "annotations",
    "axes",
    "callbacks",
    "canvas",
    "comparisons",
    "coordinates",
    "css",
    "expressions",
    "filters",
    "formatters",
    "glyphs",
    "graphs",
    "grids",
    "labeling",
    "layouts",
    "map_plots",
    "mappers",
    "misc",
    "nodes",
    "plots",
    "ranges",
    "renderers",
    "scales",
    "selections",
    "selectors",
    "sources",
    "text",
    "textures",
    "tickers",
    "tiles",
    "tools",
    "transforms",
    "ui",
    "widgets",
)

CATEGORY_TITLES = {
    "map_plots": "map plots",
    "ui/ui_element": "UI elements",
}

EXTRA_PUBLIC_API = {
    "formatters": ("bokeh.models.formatters.RELATIVE_DATETIME_CONTEXT",),
    "widgets/inputs": ("bokeh.models.widgets.inputs.ColorMap",),
}

LEGACY_CATEGORY_LABELS = {
    "plots": ("bokeh.models_plots",),
    "ui/examiner": ("bokeh.models.ui.inspector",),
}


@dataclass(frozen=True)
class ClassReference:
    name: str
    module: str
    category: str
    is_model: bool

    @property
    def target(self) -> str:
        if self.is_model:
            return f"bokeh.models.{self.name}"
        return f"{self.module}.{self.name}"

    @property
    def docname(self) -> str:
        return f"docs/reference/models/{self.category}/{self.name}/index"


def _load_public_classes() -> list[ClassReference]:
    sys.path.insert(0, str(REPO_ROOT / "src"))

    import bokeh.models as models
    from bokeh.model import Model

    classes: list[ClassReference] = []
    seen: set[type[Any]] = set()

    for name in models.__all__:
        obj = getattr(models, name)
        if not inspect.isclass(obj) or obj is Model:
            continue
        if obj in seen:
            raise RuntimeError(f"public class {obj!r} is exported under more than one name")
        seen.add(obj)
        classes.append(ClassReference(name, obj.__module__, _category_for(obj.__module__), issubclass(obj, Model)))

    classes.sort(key=lambda ref: ref.name.casefold())

    casefolded: dict[str, str] = {}
    for ref in classes:
        previous = casefolded.setdefault(ref.name.casefold(), ref.name)
        if previous != ref.name:
            raise RuntimeError(f"class page names collide on case-insensitive file systems: {previous!r} and {ref.name!r}")

    return classes


def _category_for(module: str) -> str:
    if not module.startswith("bokeh.models."):
        raise RuntimeError(f"public bokeh.models class is defined outside bokeh.models: {module}")

    parts = module.removeprefix("bokeh.models.").split(".")
    top = parts[0]

    if top in ("glyph", "glyphs"):
        return "glyphs"
    if top in ("annotations", "misc", "renderers"):
        return top
    if top in ("ui", "widgets"):
        if len(parts) < 2:
            raise RuntimeError(f"can't determine a documentation category for {module}")
        return f"{top}/{parts[1]}"
    if top not in TOP_CATEGORY_ORDER:
        raise RuntimeError(f"unknown bokeh.models documentation category: {top}")
    return top


def _category_module(category: str) -> str:
    if category == "glyphs":
        return "bokeh.models.glyphs"
    return f"bokeh.models.{category.replace('/', '.')}"


def _category_sort_key(category: str) -> tuple[int, str]:
    top, _, child = category.partition("/")
    return TOP_CATEGORY_ORDER.index(top), child


def _heading(title: str, underline: str = "#") -> str:
    return f"{title}\n{underline * len(title)}"


def _render_class_page(ref: ClassReference) -> str:
    # Standard-domain labels are case-insensitive, so a label such as
    # ``bokeh.models.Text`` collides with the ``bokeh.models.text`` module
    # label. The Python-domain object itself provides the stable top-level
    # ``bokeh.models.ClassName`` target; this label preserves module-qualified
    # references such as the existing glyph labels.
    labels = [f"{ref.module}.{ref.name}"]
    unique_labels = tuple(dict.fromkeys(labels))
    label_text = "\n".join(f".. _{label}:" for label in unique_labels)
    title = f"bokeh.models.{ref.name}"

    if ref.is_model:
        directive = f""".. bokeh-model:: {ref.name}
    :module: {ref.module}"""
        top_level_alias = ""
    else:
        directive = f""".. autoclass:: {ref.target}
    :members:
    :show-inheritance:
    :inherited-members:"""
        top_level_alias = f""".. raw:: html

    <span id="bokeh.models.{ref.name}"></span>

"""

    return f"""{GENERATED_MARKER}

{label_text}

.. meta::
    :description: API reference for {ref.target}.

{_heading(title)}

{top_level_alias}{directive}
""".strip() + "\n"


def _relative_class_doc(category: str, name: str) -> str:
    category_dir = posixpath.dirname(category)
    return posixpath.relpath(f"{category}/{name}/index", start=category_dir or ".")


def _render_category_page(category: str, refs: list[ClassReference]) -> str:
    module = _category_module(category)
    labels = [module, *LEGACY_CATEGORY_LABELS.get(category, ())]
    label_text = "\n".join(f".. _{label}:" for label in labels)
    title = CATEGORY_TITLES.get(category, category.rsplit("/", 1)[-1].replace("_", " "))

    class_items = "\n".join(
        f"* :raw-html:`<span id=\"bokeh.models.{ref.name}\"></span>` :class:`~{ref.target}`"
        for ref in refs
    )
    toctree_items = "\n".join(
        f"   {ref.name} <{_relative_class_doc(category, ref.name)}>"
        for ref in refs
    )

    extra_api = ""
    if functions := EXTRA_PUBLIC_API.get(category):
        directives = "\n\n".join(f".. autofunction:: {function}" for function in functions)
        extra_api = f"""

{_heading("Functions", "-")}

{directives}
"""

    return f"""{GENERATED_MARKER}

{label_text}

{_heading(title)}

.. automodule:: {module}

{_heading("Classes", "-")}

.. role:: raw-html(raw)
   :format: html

.. rst-class:: bokeh-model-classes

{class_items}

.. toctree::
   :hidden:
   :maxdepth: 1

{toctree_items}
{extra_api}
""".strip() + "\n"


def _render_class_index(refs: list[ClassReference]) -> str:
    targets = [("Model", "bokeh.model.Model")]
    targets.extend((ref.name, ref.target) for ref in refs)
    targets.sort(key=lambda item: item[0].casefold())
    items = [f"   * :class:`~{target}`" for _, target in targets]

    return f"""{GENERATED_MARKER}

.. _bokeh.models.classes:

{_heading("Class index")}

This is an alphabetical list of the public classes available from
:mod:`bokeh.models`. The classes are also grouped by topic in the navigation.

.. hlist::
   :columns: 3

{chr(10).join(items)}
""".strip() + "\n"


def _legacy_glyph_pages() -> dict[Path, str]:
    legacy_pages: dict[Path, str] = {}
    glyph_root = MODEL_REFERENCE_ROOT / "glyphs"

    for path in glyph_root.glob("*.rst"):
        contents = path.read_text()
        match = re.search(r"^\.\. bokeh-model:: (\w+)", contents, flags=re.MULTILINE)
        if match is None:
            match = re.search(r'data-bokeh-model-redirect="(\w+)"', contents)
        if match is None:
            raise RuntimeError(f"can't determine the class documented by legacy page {path}")
        legacy_pages[path] = match.group(1)

    return legacy_pages


def _render_legacy_redirect(name: str) -> str:
    return f"""{GENERATED_MARKER}

:orphan:
:no-search:
:no-sitemap:

.. meta::
    :robots: noindex, follow

{_heading(name)}

.. raw:: html

    <span data-bokeh-model-redirect="{name}"></span>

The reference for :class:`bokeh.models.{name}` has moved to its
:doc:`dedicated class page <{name}/index>`.
""".strip() + "\n"


def _expected_files() -> dict[Path, str]:
    refs = _load_public_classes()
    refs_by_name = {ref.name: ref for ref in refs}
    refs_by_category: defaultdict[str, list[ClassReference]] = defaultdict(list)
    for ref in refs:
        refs_by_category[ref.category].append(ref)

    expected = {MODEL_REFERENCE_ROOT / ref.category / ref.name / "index.rst": _render_class_page(ref) for ref in refs}
    expected[CLASS_INDEX_PATH] = _render_class_index(refs)

    for category in sorted(refs_by_category, key=_category_sort_key):
        expected[MODEL_REFERENCE_ROOT / f"{category}.rst"] = _render_category_page(category, refs_by_category[category])

    for path, name in _legacy_glyph_pages().items():
        if name not in refs_by_name:
            raise RuntimeError(f"legacy glyph page {path} references non-public class {name}")
        expected[path] = _render_legacy_redirect(name)

    return expected


def _generated_files() -> set[Path]:
    return {
        path
        for path in MODEL_REFERENCE_ROOT.rglob("*.rst")
        if path.read_text().startswith(GENERATED_MARKER)
    }


def _check(expected: dict[Path, str], stale: set[Path]) -> int:
    mismatches = [path for path, contents in expected.items() if not path.exists() or path.read_text() != contents]

    for path in sorted(mismatches):
        print(f"out of date: {path.relative_to(REPO_ROOT)}")
    for path in sorted(stale):
        print(f"stale: {path.relative_to(REPO_ROOT)}")

    if mismatches or stale:
        print("Run python -m tools.api_reference to update the API reference.")
        return 1
    return 0


def _write(expected: dict[Path, str], stale: set[Path]) -> None:
    for path, contents in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != contents:
            path.write_text(contents)
            print(f"updated: {path.relative_to(REPO_ROOT)}")

    for path in sorted(stale):
        path.unlink()
        print(f"removed: {path.relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the one-class-per-page bokeh.models API reference")
    parser.add_argument("--check", action="store_true", help="check that generated files are up to date")
    args = parser.parse_args()

    expected = _expected_files()
    stale = _generated_files() - set(expected)

    if args.check:
        return _check(expected, stale)

    _write(expected, stale)
    return 0


if __name__ == "__main__":
    sys.exit(main())
