#-----------------------------------------------------------------------------
# Copyright (c) Anaconda, Inc., and Bokeh Contributors.
# All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------

# Standard library imports
from typing import Literal, Unpack

# Bokeh imports
from ...core.enums import MovableType as Movable, ResizableType as Resizable
from ..dom import DOMNode
from ..nodes import Node
from .ui_element import UIElement, _UIElementInit

class _DialogInit(_UIElementInit, total=False):
    title: str | DOMNode | UIElement | None
    content: str | DOMNode | UIElement
    pinnable: bool
    collapsible: bool
    minimizable: bool
    maximizable: bool
    closable: bool
    close_action: Literal["hide", "destroy"]
    resizable: Resizable
    movable: Movable
    symmetric: bool
    top_limit: Node | None
    bottom_limit: Node | None
    left_limit: Node | None
    right_limit: Node | None

class Dialog(UIElement):
    def __init__(self, **kwargs: Unpack[_DialogInit]) -> None: ...

    title: str | DOMNode | UIElement | None = ...
    content: str | DOMNode | UIElement = ...
    pinnable: bool = ...
    collapsible: bool = ...
    minimizable: bool = ...
    maximizable: bool = ...
    closable: bool = ...
    close_action: Literal["hide", "destroy"] = ...
    resizable: Resizable = ...
    movable: Movable = ...
    symmetric: bool = ...
    top_limit: Node | None = ...
    bottom_limit: Node | None = ...
    left_limit: Node | None = ...
    right_limit: Node | None = ...
