#!/bin/bash

sudo apt-get install -y --force-yes nodejs npm redis-server libzmq3-dev

MINICONDA="Miniconda-3.0.0-Linux-x86_64"
wget http://repo.continuum.io/miniconda/$MINICONDA.sh
bash $MINICONDA.sh -b

PHANTOMJS=phantomjs-1.9.6-linux-x86_64
wget -O - https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOMJS.tar.bz2 | tar xj
mv $PHANTOMJS phantomjs
