#!/bin/bash

set -e # exit on error
set -x # echo commands

MINICONDA="Miniconda-$MINICONDA_VERSION-Linux-x86_64"
MINICONDA_URL="http://repo.continuum.io/miniconda/$MINICONDA.sh"

wget $MINICONDA_URL
bash $MINICONDA.sh -b -p $HOME/miniconda
rm -rf $MINICONDA.sh

python -V

DEPS_TRAVIS="python=$TRAVIS_PYTHON_VERSION pip nodejs conda-build jinja2"
DEPS_BOKEH="numpy pandas openpyxl<2.0 six requests dateutil"
DEPS_SERVER="flask werkzeug greenlet redis redis-py"
DEPS_DOCS="sphinx pygments" # sphinx-bootstrap-theme sphinxcontrib-napoleon
DEPS_EXAMPLES="scipy matplotlib sympy" # ggplot seaborn
DEPS_TESTS="PyYAML nose mock colorama coverage ipython ipython-notebook" # websocket
DEPS_PIP="sphinx-bootstrap-theme sphinxcontrib-napoleon"

if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
    DEPS_BOKEH="$DEPS_BOKEH abstract-rendering"
    DEPS_SERVER="$DEPS_SERVER gevent gevent-websocket"
    DEPS_PIP="$DEPS_PIP websocket"
fi

if [[ "$TRAVIS_PYTHON_VERSION" != 3.4* ]]; then
    DEPS_EXAMPLES="$DEPS_EXAMPLES statsmodels"
    DEPS_PIP="$DEPS_PIP ggplot seaborn"
fi

DEPS="$DEPS_TRAVIS $DEPS_BOKEH $DEPS_SERVER $DEPS_DOCS $DEPS_EXAMPLES $DEPS_TESTS"

conda install --quiet --yes -c bokeh $DEPS
pip install --quiet -i https://pypi.binstar.org/pypi/simple $DEPS_PIP

conda build --no-test conda.recipe
conda install --use-local bokeh

sed -i 's/^backend\s*:.*$/backend: agg/' `python -c "import matplotlib; print(matplotlib.matplotlib_fname())"`

python -c 'import bokeh; bokeh.sampledata.download(progress=False)'
