#!/bin/bash

python -c 'from bokeh import test; test()'
PYTHONPATH=$(readlink -f .) examples/test --bokeh-port=$(cat bokeh.port) --ipython-port=$(cat ipython.port) --phantomjs=phantomjs/bin/phantomjs
