#!/bin/bash

set -e # exit on error

# Setup and start Sauce Connect for your TravisCI build
# This script requires your .travis.yml to include the following two private env variables:
# SAUCELABS_USERNAME
# SAUCELABS_API_KEY

mkdir -p ~/saucelabs/sauce-connect
cd ~/saucelabs
wget https://saucelabs.com/downloads/sc-4.3.13-linux.tar.gz
tar -xzvf sc-4.3.13-linux.tar.gz --strip-components 1 --directory sauce-connect

sauce-connect/bin/sc --readyfile ~/saucelabs/sauce-connect-ready -u $SAUCELABS_USERNAME -k $SAUCELABS_API_KEY &

# Wait for Sauce Connect to be ready before exiting
while [ ! -f ~/saucelabs/sauce-connect-ready ]; do
    sleep .5
done
