#!/bin/bash

sudo apt-get install -qq -y --force-yes nodejs npm

case "$TRAVIS_PYTHON_VERSION" in
    2*) MINICONDA="Miniconda"  ;;
    3*) MINICONDA="Miniconda3" ;;
     *) exit 1
esac

MINICONDA="$MINICONDA-3.0.0-Linux-x86_64"

wget http://repo.continuum.io/miniconda/$MINICONDA.sh
bash $MINICONDA.sh -b -p $HOME/miniconda

PHANTOMJS=phantomjs-1.9.6-linux-x86_64
mkdir $HOME/phantomjs && wget -O - https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOMJS.tar.bz2 | tar xj --strip-components 1 -C $HOME/phantomjs
