#!/bin/bash

set -e # exit on error
set -x # echo commands

sudo apt-get install -qq -y --force-yes graphviz

MINICONDA="Miniconda-$MINICONDA_VERSION-Linux-x86_64"
MINICONDA_URL="http://repo.continuum.io/miniconda/$MINICONDA.sh"

wget $MINICONDA_URL
bash $MINICONDA.sh -b -p $HOME/miniconda
rm -rf $MINICONDA.sh

python -V

DEPS_TRAVIS="python=$TRAVIS_PYTHON_VERSION nodejs conda-build jinja2"
DEPS_BOKEH="numpy pandas openpyxl<2.0 six requests dateutil"
DEPS_SERVER="flask werkzeug greenlet redis redis-py"
DEPS_DOCS="sphinx pygments sphinx-bootstrap-theme sphinxcontrib-napoleon"
DEPS_EXAMPLES="scipy matplotlib sympy ggplot seaborn"
DEPS_TESTS="PyYAML nose mock colorama coverage ipython ipython-notebook pdiff websocket"

if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
    DEPS_BOKEH="$DEPS_BOKEH abstract-rendering"
    DEPS_SERVER="$DEPS_SERVER gevent gevent-websocket"
fi

DEPS="$DEPS_TRAVIS $DEPS_BOKEH $DEPS_SERVER $DEPS_DOCS $DEPS_EXAMPLES $DEPS_TESTS"

conda install -c bokeh -c mutirri --quiet --yes $DEPS

CONDA_PY="${TRAVIS_PYTHON_VERSION/./}" conda build --no-test conda.recipe
conda install --use-local --yes bokeh

MATPLOTLIB_RC=$(python -c "import matplotlib; print(matplotlib.matplotlib_fname())")
sed -i 's/^backend\s*:.*$/backend: agg/' $MATPLOTLIB_RC

python -c 'import bokeh; bokeh.sampledata.download(progress=False)'
