Listen 8080
ServerName localhost

ProxyRequests Off
ProxyPreserveHost On

ProxyPass "/myapp/ws" "ws://127.0.0.1:5100/myapp/ws"
ProxyPassReverse "/myapp/ws" "ws://127.0.0.1:5100/myapp/ws"

ProxyPass "/myapp" "http://127.0.0.1:5100/myapp"
ProxyPassReverse "/myapp" "http://127.0.0.1:5100/myapp"
