Listen 8080

<VirtualHost *:8080>
    ServerName localhost

    ProxyRequests Off
    ProxyPreserveHost On

    ProxyPass "/services/bokeh/myapp/ws" "ws://127.0.0.1:5100/services/bokeh/myapp/ws"
    ProxyPassReverse "/services/bokeh/myapp/ws" "ws://127.0.0.1:5100/services/bokeh/myapp/ws"

    ProxyPass "/services/bokeh/" "http://127.0.0.1:5100/services/bokeh/"
    ProxyPassReverse "/services/bokeh/" "http://127.0.0.1:5100/services/bokeh/"
</VirtualHost>
