{% set data = load_setup_py_data() %}

package:
  name: bokeh
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  entry_points:
    - bokeh = bokeh.__main__:main

extra:
  channels:
    - bokeh
    - conda-forge

requirements:
  build:
    - jinja2
    - nodejs >=14
    - numpy
    - packaging
    - python
    - python-dateutil
    - pyyaml
    - ripgrep
    - setuptools
    - tornado >=5
    - yaml

  host:
    - python >=3.7

  run:
    - python >=3.7

    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  commands:
    - bokeh -h

  imports:
    - bokeh

about:
  home: https://www.bokeh.org
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
  description: |
    Bokeh is a Python library for creating interactive visualizations
    for modern web browsers. It helps you build beautiful graphics,
    ranging from simple plots to complex dashboards with streaming
    datasets. With Bokeh, you can create JavaScript-powered visualizations
    without writing any JavaScript yourself.
  doc_url: https://docs.bokeh.org
  dev_url: {{ data['url'] }}
