package:
  name: bokeh
  version: 'nightly'

build:
  number: {{ environ.get('BINSTAR_BUILD', 1) }}

extra:
  channels:
    - bokeh

requirements:
  build:
    - python
    - distribute
    - setuptools
    - nodejs >=4.1

  run:
    # bokeh
    - python
    - six
    - requests
    - pyyaml
    - python-dateutil
    - jinja2
    - numpy
    - pandas

    # server
    - flask
    - pyzmq
    - tornado >=4.0.1
    - futures        [py27]

test:
  requires:
    # docs
    - graphviz
    - pygments
    - sphinx >=1.3.1
    - sphinx-bootstrap-theme
    - sphinxcontrib-httpdomain

    # tests
    # pyyaml installed by bokeh
    # jinja2 installed by bokeh
    - colorama
    - coverage
    - flake8
    - mock
    - pytest
    - pytest-cov ==1.8.1
    - pytest-selenium ==1.0b1
    - abstract-rendering        [not win]
    - beautiful-soup
    - websocket-client
    - blaze
    - multiuserblazeserver
    - scipy
    - pillow

    # examples
    - ipython
    - ipython-notebook
    - matplotlib
    - sympy
    - ggplot
    - seaborn
    - icalendar

  commands:
    - bokeh -h        [linux64 or osx]

  imports:
    - bokeh

about:
  home: https://github.com/bokeh/bokeh
  license: New BSD
