{% set data = load_setup_py_data() %}

package:
  name: bokeh
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  entry_points:
    - bokeh = bokeh.__main__:main

extra:
  channels:
    - bokeh
    - conda-forge

requirements:
  build:
    - python
    - setuptools
    - nodejs >=6.10.0
    - certifi
    - pycurl
    - packaging
    - six
    - python-dateutil
    - numpy
    - yaml
    - pyyaml
    - jinja2
    - tornado >=4.3

  run:
    - python

    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

    # meta-package installs futures for 2.7 but not for 3.x
    # needed in order to be able to build no-arch conda packages
    - futures-compat

test:
  requires:
    # docs
    - colorcet
    - pygments
    - sphinx <1.6
    # pyyaml installed by bokeh
    # packaging installed by bokeh

    # tests
    - colorama
    - coverage
    - flake8
    - lxml
    - networkx
    - mock
    - packaging
    - pandas
    - pytest >=3.0.2
    - pytest-catchlog >=1.2.2
    - pytest-cov >=1.8.1
    - pytest-selenium >=1.6.0 [unix]
    - pytest-html
    - selenium >=3
    - pytest-xdist
    - pytest-rerunfailures
    - requests >=1.2.3
    - beautifulsoup4
    - scipy
    - numba
    - pillow
    - boto
    - nodejs >=6.10.0
    # pyyaml installed by bokeh
    # jinja2 installed by bokeh

    # examples
    - notebook
    - sympy
    - scikit-learn
    - networkx
    - icalendar
    - flask
    - flexx
    - pyshp

  commands:
    - bokeh -h

  imports:
    - bokeh

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
