{% set data = load_setup_py_data() %}

package:
  name: bokeh
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  entry_points:
    - bokeh = bokeh.__main__:main

extra:
  channels:
    - bokeh
    - conda-forge

requirements:
  build:
    - jinja2
    - nodejs >=8.8
    - numpy
    - packaging
    - python
    - python-dateutil
    - pyyaml
    - ripgrep
    - setuptools
    - tornado >=5
    - yaml

  run:
    - python

    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

    # meta-package installs futures for 2.7 but not for 3.x
    # needed in order to be able to build no-arch conda packages
    - futures-compat

test:
  requires:
    # jinja2 installed by bokeh
    # packaging installed by bokeh
    # pyyaml installed by bokeh

    # docs
    - colorcet
    - pygments
    - sphinx >=1.8

    # tests
    - beautifulsoup4
    - boto
    - colorama
    - coverage
    - flake8
    - lxml
    - mock
    - nbconvert >=5.4
    - networkx
    - nodejs >=8.8
    - numba
    - pandas
    - psutil
    - pytest
    - pytest-cov >=1.8.1
    - pytest-html
    - pytest-xdist
    - requests >=1.2.3
    - selenium=3.8.0
    - scipy

    # examples
    - flask >=1.0
    - django
    - h5py
    - icalendar
    - networkx
    - notebook
    - opencv
    - pscript
    - pyshp
    - scikit-learn
    - sympy

  commands:
    - bokeh -h

  imports:
    - bokeh

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}

extra:
  deploy:
    - anaconda-client
    - setuptools >=0.39
    - twine >=1.11
