package:
  name: bokeh
  version: 'nightly'

build:
  number: {{ environ.get('BINSTAR_BUILD', 1) }}

requirements:
  build:
    - python
    - distribute
    - setuptools
    - nodejs

  run:
    # bokeh
    - python
    - numpy
    - pandas
    - six
    - requests
    - dateutil
    - pyyaml

    # server
    - flask
    - werkzeug
    - greenlet
    - redis
    - redis-py
    - gevent               [py2k]
    - gevent-websocket     [py2k]
    - abstract-rendering   [py2k]

test:
  requires:
    # docs
    - sphinx
    - pygments
    - sphinx-bootstrap-theme
    - sphinxcontrib-napoleon

    # tests
    - colorama
    - pyyaml
    - pdiff
    - boto
    - jinja2
    - nose
    - mock
    - coverage
    - websocket
    - ipython
    - ipython-notebook

    # examples
    - scipy
    - matplotlib
    - sympy
    - ggplot
    - seaborn

  commands:
    - bokeh-server -h        [linux64 or osx]

  imports:
    - bokeh

about:
  home: https://github.com/ContinuumIO/Bokeh
  license: New BSD
