name: Bokeh-Docker-Test

on:
  push:
    branches:
      - main
      - branch-*
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: bokeh/bokeh-dev:branch-3.1

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full history to get proper build version

      - name: Start Docker container, build Bokeh and run tests.
        env:
          BOKEH_DOCKER_BUILD: 1
          BOKEH_DOCKER_TEST: 1
          BOKEH_DOCKER_INTERACTIVE: 0
        run: |
          scripts/docker/docker_run.sh $IMAGE_TAG

      - name: Collect results
        shell: bash
        run: |
          SRC="bokehjs/test/baselines/linux"
          DST="bokeh-report-docker/${SRC}"
          mkdir -p ${DST}
          if [[ -e ${SRC}/report.json ]];
          then
            CHANGED=$(git status --short ${SRC}/\*.blf ${SRC}/\*.png | cut -c4-)
            cp ${SRC}/report.json ${CHANGED} ${DST}
          fi

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: bokeh-report-docker
          path: bokeh-report-docker
