from __future__ import annotations

# Standard library imports
from typing import Any, TypedDict

class ViewportSize(TypedDict):
    width: int
    height: int

class FloatRect(TypedDict):
    x: float
    y: float
    width: float
    height: float

class BrowserType:
    async def launch(self, *, args: list[str] | None = None) -> Browser: ...

class Playwright:
    chromium: BrowserType
    async def stop(self) -> None: ...

class PlaywrightContextManager:
    async def start(self) -> Playwright: ...

class Browser:
    async def close(self) -> None: ...
    def is_connected(self) -> bool: ...
    async def new_page(self) -> Page: ...

class Page:
    async def close(self) -> None: ...
    async def evaluate(self, expression: str) -> Any: ...
    async def goto(self, url: str) -> None: ...
    def is_closed(self) -> bool: ...
    async def screenshot(self, *, clip: FloatRect | None = None) -> bytes: ...
    async def set_viewport_size(self, viewport_size: ViewportSize) -> None: ...
    async def wait_for_function(self, expression: str, *, timeout: float | None = None) -> Any: ...

def async_playwright() -> PlaywrightContextManager: ...
